build.gradle, gradle/spotbugs-exclude.xml
Add a spotbugs-exclude file to filter on JsonSchema from the name shadow check.
=> INTERLOK-2658 Add JsonSchema as an exclude since it is deprecated

src/main/java/com/adaptris/core/json/jdbc/BatchInsertJsonArray.java, src/main/java/com/adaptris/core/json/jdbc/InsertJsonArray.java, src/main/java/com/adaptris/core/json/jdbc/InsertJsonObject.java, src/main/java/com/adaptris/core/json/jdbc/UpsertJsonArray.java, src/main/java/com/adaptris/core/json/jdbc/UpsertJsonObject.java, src/test/java/com/adaptris/core/json/jdbc/BatchJsonArrayInsertTest.java, src/test/java/com/adaptris/core/json/jdbc/InsertJsonArrayTest.java, src/test/java/com/adaptris/core/json/jdbc/InsertJsonObjectTest.java, src/test/java/com/adaptris/core/json/jdbc/JdbcJsonInsertCase.java, src/test/java/com/adaptris/core/json/jdbc/UpsertJsonArrayTest.java, src/test/java/com/adaptris/core/json/jdbc/UpsertJsonObjectTest.java
- Add support for the rows-affected-metadata-key in JSON insert/upsert
- Refactor the executeBatch method for coverage.
=> INTERLOK-2759 Add support for rows-affected-metadata-key

src/main/java/com/adaptris/core/json/aggregator/JsonArrayAggregator.java, src/main/java/com/adaptris/core/json/aggregator/JsonArrayArrayAggregator.java, src/test/java/com/adaptris/core/json/aggregator/JsonArrayAggregatorFilterTest.java, src/test/java/com/adaptris/core/json/aggregator/JsonArrayAggregatorTest.java, src/test/java/com/adaptris/core/json/aggregator/JsonArrayArrayAggregatorTest.java, src/test/resources/growers-sync16.json
This code requires the latest pull requests on interlok-core: new conditionals and filter-splitter3 otherwise compilation will fail.
The following aggregators have been updated to filter the messages with an optional condition, tests have been added.
This pull requests goes together with the interlok-core equivalent one.
=> Interlok-2852 added filter condition to aggregator

build.gradle, src/main/java/com/adaptris/core/json/exception/ExceptionAsJson.java, src/main/java/com/adaptris/core/transform/json/MetadataToJsonService.java, src/test/java/com/adaptris/core/transform/json/MetadataToJsonServiceTest.java
- Uses PrintWriter.println() which means it will be platform dependent
- Make ExceptionAsJson use try-with-resources
- Upgrade mockito
This makes me 😢 but it would appear that so-called streaming isn't streaming in the classical sense;
=> INTERLOK-2924 Add option to add a trailing newline

.github/workflows/gradle.yml, src/main/java/com/adaptris/core/json/jdbc/BatchInsertJsonArray.java, src/main/java/com/adaptris/core/json/jdbc/InsertJsonArray.java, src/main/java/com/adaptris/core/json/jdbc/InsertJsonObjects.java, src/main/java/com/adaptris/core/json/jdbc/UpsertJsonArray.java, src/main/java/com/adaptris/core/json/jdbc/UpsertJsonObjects.java, src/main/java/com/adaptris/core/services/splitter/json/JsonProvider.java, src/test/java/com/adaptris/core/json/jdbc/InsertJsonArrayTest.java, src/test/java/com/adaptris/core/json/jdbc/UpsertJsonArrayTest.java, src/test/java/com/adaptris/core/services/splitter/json/JsonProviderTest.java
Add a JsonProvider interface that contains a couple of enums that allow us to switch between JSON_LINES and JSON_ARRAY.
- json.jdbc.* now uses the JsonProvider where it prevviously just used the large-array-splitter
- json-to-csv can use this.
- However, the elastic ones are tricksy since they parse the JSON directly themslves; so this might have a larger scope of impact.
=> INTERLOK-2892 Add JSON Array / Lines support.

.gitignore, src/main/java/com/adaptris/core/json/JsonPathExecution.java, src/main/java/com/adaptris/core/services/path/json/JsonPathService.java, src/test/java/com/adaptris/core/services/path/json/JsonPathServiceTest.java
If you have the document 
```
{
"LastModifiedDate": "2017-11-23T15:15:31.000+0000",
"WhatId": null,
"Description": "wanted more info on ebusiness and agility including analytical models"
}
```
And you use json-path-service to extract `$.WhatId`'; it returns you a null object (correctly, since it is). You can't suppress it, because the path is found... Subsequently we  call null.toString() which causes a NullPointerException and the service fails.
We can work around this by having continue-on-fail etc; but that still leaves you with metadata that needs to be defaulted.
Add a null-converter to `json-path-execution` which is then used at execution time by json-path-service. 
The default behaviour is to turn nulls into the string "null". This seems a reasonable default (but note that this is …
=> INTERLOK-3205 Add NullConverter to JsonPathService

src/main/java/com/adaptris/core/json/resolver/FromPayloadUsingJSONPath.java, src/main/resources/META-INF/services/com.adaptris.interlok.resolver.Resolver, src/test/java/com/adaptris/core/json/resolver/FromPayloadUsingJSONPathTest.java
Using the same package as the resolver in interlok-core causes issues with the JavaDoc.
Move the JSON resolver package.
The JavaDoc should no longer be broken.
https://nexus.adaptris.net/nexus/content/sites/javadocs/com/adaptris/interlok-json/3.11.0-RELEASE/com/adaptris/core/resolver/package-summary.html should not include broken JavaDoc links.
=> INTERLOK-3434 Change package of resovler class

interlok-json/src/main/java/com/adaptris/core/json/aggregator/JsonAggregatorImpl.java, interlok-json/src/main/java/com/adaptris/core/json/aggregator/JsonArrayAggregator.java, interlok-json/src/main/java/com/adaptris/core/json/aggregator/JsonArrayArrayAggregator.java, interlok-json/src/main/java/com/adaptris/core/json/aggregator/JsonMergeAggregator.java, interlok-json/src/test/java/com/adaptris/core/json/aggregator/JsonArrayAggregatorFilterTest.java, interlok-json/src/test/java/com/adaptris/core/json/aggregator/JsonArrayAggregatorTest.java, interlok-json/src/test/java/com/adaptris/core/json/aggregator/JsonArrayArrayAggregatorTest.java, interlok-json/src/test/java/com/adaptris/core/json/aggregator/JsonMergeAggregatorTest.java
Because of https://github.com/adaptris/interlok/pull/524 there is a new aggregate() method that works on Iterable rather than Collections (for lazy iteration with large messages / joins).
The various JSON aggregators should support this rather than relying on the default behaviour which doesn't change the performance characteristics.
c.f. : https://github.com/adaptris/interlok-csv/pull/88
- Directly implement aggregate() method that is now defined in MessageAggregator.  
- joinMessage() delegates to it
- Change branching logic in JsonArrayArrayAggregator for coverage purposes, we can't fire the else condition; since if it's not json it will throw a JsonParseException.
- More tests.
No visible change for the user.
Unit tests pass and any existing configuration should work.
=> INTERLOK-3424 - Implement aggregate method from interface.

interlok-json/src/main/java/com/adaptris/core/json/schema/ModifyPayloadExceptionHandler.java, interlok-json/src/test/java/com/adaptris/core/json/schema/JsonSchemaServiceTest.java
If there is only a single violation in the input JSON, there are duplicate error messages in the response [as ```.getAllMessages()``` returns the same as ```.getMessage()```]
If there is only 1 item returned from ```.getAllMessages()``` then ignore it, as it will be the same as returned by ```.getMessage()```.
The result is that there are not duplicate error messages.
The update to ```JsonSchemaServiceTest.assertModifications(…)``` confirmed that duplicates were present and and now no longer included.
=> INTERLOK-3484 - Remove duplicate messages

interlok-json/src/main/java/com/adaptris/core/services/splitter/json/JsonProvider.java, interlok-json/src/main/java/com/adaptris/core/transform/json/JsonArrayToJsonLines.java, interlok-json/src/main/java/com/adaptris/core/transform/json/JsonLinesToJsonArray.java, interlok-json/src/test/java/com/adaptris/core/transform/json/JsonArrayToJsonLinesTest.java, interlok-json/src/test/java/com/adaptris/core/transform/json/JsonLinesTest.java, interlok-json/src/test/java/com/adaptris/core/transform/json/JsonLinesToJsonArrayTest.java
JSON_LINES is a thing
JSON-ARRAY is a thing
we need to be able to transform between the 2.
- Add a JsonLinesToJsonArray service
- Add a JsonArrayToJsonLines service
Since `-array` is special to XStream; we can't have an XStreamAlias that ends with -array; so the aliases of the classes don't necessarily "match" the service name.
New services that are available to configure.
```
<json-array-to-lines-transform/>
<json-lines-to-array-transform/>
```
Should give you "semantically similar" output.
=> INTERLOK-3427 Add JSON_LINES / JSON_ARRAY transform capability

interlok-json/src/main/java/com/adaptris/core/transform/json/DefaultJsonTransformationDriver.java
Config components are marked as being removed in 3.12.0 but these changes are now being delayed until 4.0.0
updated the ConfigDeprecated/Removal annotations
any warnings generated from config checker / ui will be correct
just eyeball the changes and make sure nothing stupid was done
=> updated the ConfigDeprecated/Removal annotations; from 3.12 to 4

interlok-json/build.gradle
The documentation was broken since we changed the doc site
Fix the doc url
The pom has a correct doc url
Check that the new url exists in the interlok-json POM file after running gradle generatePomFileForMavenJavaPublication.
=> INTERLOK-3555 Update the pom url to point to the right doc page

interlok-json/build.gradle
Use the latest derby version that integrates better with java11
Upgrade derby to 10.15.2.0
Nothing should change on how Interlok json works
Tests should pass
=> INTERLOK-2963 #comment Upgrade Derby DB to 10.15.2.0

interlok-json/src/test/java/com/adaptris/core/json/resolver/FromPayloadUsingJSONPathTest.java
Following the merge of [interlok-3567](https://github.com/adaptris/interlok/pull/621) there was a knock-on effect. In this instance it was an anonymous instance of AdaptrisMessage in a unit test missing a new method `resolveObject(String)`.
Add new `resolveObject(String)` method to test object.
The test will now compile and execute as expected.
Run the unit tests `gradle build`
=> INTERLOK-3567 Add resolveObject method to test object

interlok-json-streaming/build.gradle, interlok-json-streaming/src/main/java/com/adaptris/core/json/streaming/JsonPathStreamingService.java, interlok-json-streaming/src/test/java/com/adaptris/core/json/streaming/JsonPathStreamingServiceTest.java, interlok-json/src/main/java/com/adaptris/core/services/path/json/JsonPathService.java, interlok-json/src/main/java/com/adaptris/core/services/path/json/JsonPathServiceImpl.java, interlok-json/src/test/java/com/adaptris/core/services/path/json/JsonPathServiceTest.java
An alternative to Jayway JSON Path, that doesn't require parsing the entire JSON document, ideally works on streams.
Add JSON path service that uses JSON Surfer to parse JSON as a stream and extract data using JSON path syntax. Unit tests cloned from original JSON path service.
The end user should now be able to query unfathomably large JSON documents with JSON path syntax and get results.
The unit tests are cloned from the original JSON path service tests, just with references to the new service. There is also a [config](https://github.com/adaptris/interlok-json/files/6432500/adapter.xml.txt) that, at the very least, demonstrates that the new streaming JSON path service can extract data just as well as the original.
=> INTERLOK-3333 JsonPath on large JSON (streaming)

interlok-json-streaming/build.gradle, interlok-json-streaming/src/main/java/com/adaptris/core/json/streaming/JsonPathStreamingService.java, interlok-json-streaming/src/test/java/com/adaptris/core/json/streaming/JsonPathStreamingServiceTest.java
Since fastjson exposes a jersey service provider this interferes with the UI because of classloader issues.
There are alternatives to fastjson (gson/jackson/simple) so we can remove it since we don't have a hard dependency on it to assist with streaming json path
This was caused by : https://github.com/adaptris/interlok-json/pull/201
Remove `FAST` from the Surfer enum
Modify tests so that they don't refer to it (using JACKSON instead).
The UI now starts if you have a dependency on interlok-json-streaming
Using the normal develop snapshot. UI doesn't start.
Build using this version, delete fastjson.jar (since it will no longer be part of the dependencies). The UI now starts.
=> INTERLOK-3782 Remove fastjson dependency

interlok-json/src/main/java/com/adaptris/core/transform/json/JsonArrayToJsonLines.java, interlok-json/src/test/java/com/adaptris/core/transform/json/JsonLinesTest.java
Fixes https://github.com/adaptris/interlok-json/issues/260
Rather than using JsonUtil.mapifyJson which is clearly the wrong thing to use, we create a JsonParser, read each message, and emit the resulting ObjectNode as appropriate.
Bug fix.
Test as per : https://github.com/adaptris/interlok-json/issues/260
=> Fix JsonArray to Json lines behaviour so nested objects are not treated as strings.

interlok-json-streaming/build.gradle
snyk.io has reported vulns in gson + junit.
- https://security.snyk.io/vuln/SNYK-JAVA-COMGOOGLECODEGSON-1730327
- https://security.snyk.io/vuln/SNYK-JAVA-JUNIT-1017047
junit should never be a runtime dependency anyway.
- Remove transitive dependency on junit which was awful anyway.
- Add exclusion for gson, and opt for explicit dependency.
No change for the end user.
Tests pass; inspect the snyk.io report in the checks for this PR.
=> Fix snyk.io vulnerability reports in gson + junit.

interlok-jq/build.gradle, interlok-jq/src/main/java/com/adaptris/core/json/jq/JsonJqTransform.java, interlok-jslt/src/main/java/com/adaptris/core/json/jslt/JsltQuery.java, interlok-json-streaming/src/main/java/com/adaptris/core/json/streaming/JsonPathStreamingService.java, interlok-json/src/main/java/com/adaptris/core/services/splitter/json/JsonObjectSplitter.java, interlok-json/src/main/java/com/adaptris/core/services/splitter/json/LargeJsonArrayPathSplitter.java, interlok-json/src/main/java/com/adaptris/core/services/splitter/json/LargeJsonArraySplitter.java, interlok-json/src/main/java/com/adaptris/core/transform/json/JsonTransformService.java, interlok-json/src/main/java/com/adaptris/core/transform/json/SafeJsonTransformationDriver.java, interlok-json/src/main/java/com/adaptris/core/transform/json/SimpleJsonTransformationDriver.java, interlok-json/src/main/java/com/adaptris/core/transform/json/TransformationDirection.java
There is now a preview release of JQ version 1. As it is incompatible with previous releases it is worth seeing how much is going to need changing in interlok-jsjon-jq.
Update the dependency in build.gradle and update usage in the JsonJqTransform class.
There should be no noticeable change for the end user.
[Simple config](https://github.com/adaptris/interlok-json/files/7177860/adapter.xml.txt) that demonstrates no change for end user.
=> INTERLOK-3815 Start using version 1.0.0-preview of JQ

interlok-json/src/main/java/com/adaptris/core/transform/json/XMLSerializer.java, interlok-json/src/test/java/com/adaptris/core/transform/json/JsonXmlTransformServiceTest.java
Sufficiently large Integers get converted to Double and then expressed in scientific notation when converting from XML to JSON.
Instead of using an Integer, the conversion now uses a Long. Also, add unit tests (which seem to suggest that it isn't such a problem converting from JSON to XML).
Values too large for an Integer don't get converted to a Double and end up in scientific notation.
[This config](https://github.com/adaptris/interlok-json/files/7677423/adapter.xml.txt) can be used to highlight the error, and then the solution.
=> INTERLOK-3852 Use long instead of integer

interlok-json/src/main/java/com/adaptris/core/json/resolver/SaferJSONResolver.java, interlok-json/src/main/resources/META-INF/services/com.adaptris.interlok.resolver.Resolver, interlok-json/src/test/java/com/adaptris/core/json/resolver/SaferJSONResolverTest.java
What if the resolved data isn't safe for JSON? It should be escaped, particularly if there are quotation marks within the data.
Add new resolver that will ensure that the resolved data is JSON safe.
(Hopefully) the user can now include whatever they want when resolving into a JSON document.
[Sample config](https://github.com/adaptris/interlok-json/files/7821836/adapter.xml.txt) that will resolve metadata and insert in into the JSON payload. Used in combination with the [new XML resolver](https://github.com/adaptris/interlok/pull/867).
NB The config will need updating to use `%asJSONString{...}`
=> interlok-2752 Add new JSON resolver

build.gradle, interlok-json/build.gradle
everit-json-schema has moved from jitpack to mavenCentral and into the group `com.github.erosb`
jitpack is still usable, but it may be better to rely on his formal release artifacts in case he decides not to build via github-release.
Changed group-id / artifact name in interlok-json
Remove jitpack.io as a gradle repo.
No change for the end user
`gradle check` passes.
=> Switch to formal mavencentral artefact

interlok-json/src/test/java/com/adaptris/core/json/resolver/FromPayloadUsingJSONPathTest.java
Add changes required by https://github.com/adaptris/interlok/pull/950
Fix unit test (the style is ashleys) that has an anonymous InterlokMessage impl.
No change for the end user of Interlok
`./gradlew compileTestJava` now works.
=> fix(junit): Add missing method from API change

interlok-json/src/main/java/com/adaptris/core/json/ForEachJsonArrayElementService.java, interlok-json/src/main/java/com/adaptris/core/json/JsonParseModeEnum.java, interlok-json/src/test/java/com/adaptris/core/json/ForEachJsonArrayElementServiceTest.java
We needed a way to execute a configured service for each json array element in a given data source.
There are other options like Json array splitters, however if you don't want a cloned message for each invocation, then the splitter doesn't work for your needs.
New service to perform a loop for each array element and a new configurable enum to set the Json parse mode.
=> Added a new service that executes a configured service for each Json array element
